# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1skrAnI8uHtbDYVw02Ny1hew9s0rHqo1N

# **Building the Web App (Streamlit)**
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

st.title("Student Performance Analysis")

st.write(
    "This application shows exploratory data analysis and model results "
    "for student performance data."
)

# Load dataset
df = pd.read_csv("The_Real_Student_Performance.csv")

st.header("Dataset Overview")
st.write("Rows:", df.shape[0])
st.write("Columns:", df.shape[1])
st.dataframe(df.head())

st.header("Final Grade Distribution")
fig1, ax1 = plt.subplots()
sns.countplot(x="final_grade", data=df, ax=ax1)
st.pyplot(fig1)

st.header("Study Hours vs Overall Score")
fig2, ax2 = plt.subplots()
sns.scatterplot(
    x="study_hours", y="overall_score", data=df, alpha=0.4, ax=ax2
)
st.pyplot(fig2)

st.header("Model Used")
st.write(
    "Random Forest Classifier was selected as the final model "
    "based on highest accuracy and balanced performance."
)